//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int PK_Bitacora { get; set; }
        public int FK_Bitacora_Usuario { get; set; }
        public string movimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
