//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int PK_Telefono { get; set; }
        public Nullable<int> FK_Telefono_Persona { get; set; }
        public Nullable<int> FK_Telefono_Usuario { get; set; }
        public string tipo { get; set; }
        public Nullable<int> numero { get; set; }
        public string correo { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
