//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoAdjunto
    {
        public int PK_DocAdjunto { get; set; }
        public int FK_DocAdjunto_Expediente { get; set; }
        public byte[] documento { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
