//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expediente()
        {
            this.DocumentoAdjunto = new HashSet<DocumentoAdjunto>();
            this.Implicado = new HashSet<Implicado>();
            this.Seguimiento = new HashSet<Seguimiento>();
            this.TipoDemanda = new HashSet<TipoDemanda>();
        }
    
        public int PK_Expediente { get; set; }
        public Nullable<int> FK_Expediente_Cita { get; set; }
        public int FK_Expediente_Usuario { get; set; }
        public Nullable<int> FK_Expediente_Estado { get; set; }
        public Nullable<int> FK_Exp_AtencionBrindada { get; set; }
        public Nullable<int> FK_Exp_Procedimientos { get; set; }
        public string intervencionRealizada { get; set; }
        public string valoracion { get; set; }
        public string secuelas { get; set; }
        public string observaciones { get; set; }
    
        public virtual Cita Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoAdjunto> DocumentoAdjunto { get; set; }
        public virtual ProcedimientoLegal ProcedimientoLegal { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implicado> Implicado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoDemanda> TipoDemanda { get; set; }
    }
}
