//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implicado
    {
        public int PK_Implicado { get; set; }
        public int FK_Implicado_Persona { get; set; }
        public int FK_Implicado_Tipo { get; set; }
        public Nullable<int> FK_Implicado_Expediente { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
    }
}
